"""Typed models used across server, resolver, and client."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any

JSONValue = None | bool | int | float | str | list["JSONValue"] | dict[str, "JSONValue"]


@dataclass(frozen=True, slots=True)
class SearchArgs:
    """Arguments for ECOS StatisticSearch."""

    table_code: str
    cycle: str
    start_date: str
    end_date: str
    item_code1: str = "?"
    item_code2: str = "?"
    item_code3: str = "?"
    org_code: str = "?"

    def to_dict(self) -> dict[str, str]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class ResolutionCandidate:
    """Candidate result generated by the query resolver."""

    alias: str
    score: int
    confidence: float
    reasons: list[str]
    search_args: SearchArgs

    def to_dict(self) -> dict[str, Any]:
        return {
            "alias": self.alias,
            "score": self.score,
            "confidence": self.confidence,
            "reasons": self.reasons,
            "search_args": self.search_args.to_dict(),
        }


@dataclass(frozen=True, slots=True)
class SourceMetadata:
    """Attribution metadata for transformed responses."""

    name: str = "Bank of Korea ECOS"
    organization: str = "한국은행"
    url: str = "https://ecos.bok.or.kr/"
    attribution: str = "Source: Bank of Korea ECOS API (https://ecos.bok.or.kr/)"

    def to_dict(self) -> dict[str, str]:
        return asdict(self)


@dataclass(slots=True)
class Envelope:
    """Standard response envelope used by all major tools."""

    ok: bool
    data: dict[str, Any]
    request: dict[str, Any]
    source: SourceMetadata = field(default_factory=SourceMetadata)
    warnings: list[str] = field(default_factory=list)
    transformed_fields: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "ok": self.ok,
            "request": self.request,
            "data": self.data,
            "source": self.source.to_dict(),
            "warnings": self.warnings,
            "transformed": {
                "normalized_at": datetime.now(timezone.utc).isoformat(),
                "fields": self.transformed_fields,
            },
        }
